name: uikit
description: "Ui kit for project"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  awesome_extensions: ^2.0.17
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.7.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/src/assets
  line_length: 100

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: TestTaskAssets

  integrations:
    flutter_svg: true
